spring:
  application:
    name: aicodehelper
  profiles:
    active: local
langchain4j:
  open-ai:
    chat-model:
      api-key: demo
      base-url: http://langchain4j.dev/demo/openai/v1
      model-name: gpt-4o-mini
    streaming-chat-model:
      model-name: openai-gpt-4o
      api-key: <Your API Key>
    embedding-model:
      model-name: text-embedding-v4
      api-key: <Your API Key>
bigmodel:
  api-key: <Your API Key>